//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.23 at 11:15:21 PM MSK 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.borodinov.ru/spring/ws/users", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.gb.spring.wintermarket.soap;
